name: pdns-renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
 
concurrency: pdns-renovate

jobs:
  renovate:
    runs-on: default
    steps:
    
      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        run:  renovate
        env:
          GOPROXY: https://artifactory.internal.cba/org.golang.proxy
          GOSUMDB: off
          RENOVATE_TOKEN: ${{ steps.generate-token.outputs.token }}
          RENOVATE_ARTIFACTORY_PUBLIC_PASSWORD: ${{env.ARTIFACTORY_PASSWORD}}
          RENOVATE_CONFIG_FILE: pdns-renovate-config.js
          RENOVATE_TIMEZONE: Australia/Sydney
          LOG_LEVEL: debug
          LOG_FORMAT: jsonname: pdns-renovate
