name: pdns-renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
 
concurrency: pdns-renovate

jobs:
  renovate:
    runs-on: default
    steps:
      - name: Get Id Token from Vault
        id: id-token
        uses: hashicorp/vault-action@a1b77a09293a4366e48a5067a86692ac6e94fdc0 # v3.1.0
        with:
          method: jwt
          path: jwt_github-repository
          url: https://vault.ai.cba
          role: default
          tlsSkipVerify: true
          secrets: |
            appinfra/vh-pdns-vault/kv/data/tokens/dev acoe_vhdns_build | ARTIFACTORY_PASSWORD ;
            appinfra/vh-pdns-vault/kv/data/tokens/stg GH_APP_ID | GH_APP_ID ;
            appinfra/vh-pdns-vault/kv/data/tokens/stg GH_APP_PRIVATE_KEY | GH_APP_PRIVATE_KEY

      - name: Generate token for renovate to manage pdns repos
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1
        id: generate-token
        with:
          app-id: ${{ env.GH_APP_ID }}
          private-key: ${{ env.GH_APP_PRIVATE_KEY }}  
          owner: CBA-General
   
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version: '1.20'

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: '20.15.1'
          cache: npm
          cache-dependency-path: .github/package-lock.json

      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        run:  renovate
        env:
          GOPROXY: https://artifactory.internal.cba/org.golang.proxy
          GOSUMDB: off
          RENOVATE_TOKEN: ${{ steps.generate-token.outputs.token }}
          RENOVATE_ARTIFACTORY_PUBLIC_PASSWORD: ${{env.ARTIFACTORY_PASSWORD}}
          RENOVATE_CONFIG_FILE: pdns-renovate-config.js
          RENOVATE_TIMEZONE: Australia/Sydney
          LOG_LEVEL: debug
          LOG_FORMAT: jsonname: pdns-renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
 
concurrency: pdns-renovate

jobs:
  renovate:
    runs-on: default
    steps:

      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        run:  renovate
        env:
          RENOVATE_TIMEZONE: Australia/Sydney
          LOG_LEVEL: debug
          LOG_FORMAT: json
