name: pdns-renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
 
concurrency: pdns-renovate

jobs:
  renovate:
    runs-on: default
    steps:
    
      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        run:  renovate
        env:
          RENOVATE_TIMEZONE: Australia/Sydney
          LOG_LEVEL: debug
          LOG_FORMAT: json
